### ISSUE TITLE
Running inference on longer samples

### ISSUE THREAD

**Issue by oferfish** [ShariqM/source_separation#2]
How should I modify the code to be able to run longer samples in the inference test as is mentioned in the paper?
Additionally, where are the inferred output sound files saved?
Thanks
P.S. when running in run_inference_test=True, it throws an error where the tensor shape is too small for the reshape. I solved this by removing:
kmeans_mask = helper.uncollapse_freq_into_time(hparams, kmeans_mask)
from setup_eval_results_summary in summaries.py

**Comment by ShariqM** [comment]
Hi @oferfish,
You can increase ntimebins in hyperparameters.py, 133 time bins is about 1 second (according to the current STFT parameters in constants.py)

The waveforms are saved in waveforms/ (you can see this in save_waveforms() in train.py)

Thanks for the error notification, I fixed it in the last commit. Let me know if you have an issues, thanks for your interest!

commit id: 3ecd8b26a7bbcb174eb6f133b7d5e31b181875ee

**Comment by oferfish** [comment]
Thank you, I have seen where the waveforms are saved during training, I couldn't find where they are saved when running the run_inference in inference.py.
When running in inference mode on a small sample of sound files, I haven't found where the waveforms are saved or how to stop running when the the sample data has finished running. Also how do you chose the checkpoint to use when running inference?
Your work is very interesting, thank you for your continued support.

**Comment by ShariqM** [comment]
oh, you're right, they are not saved in the instance case. I would normally just view the output in the TensorBoard.

you can call python main.py -l EXPERIMENT_NUM
to  load the checkpoint correspond to that experiment. The experiment number should be output when you start training

**Comment by oferfish** [comment]
When running inference, the output in TensorBoard is only for the k-means and not for the attractor.
